### ISSUE TITLE
Fix formatting - unnecessary indents?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Exceptions#109]
* https://docs.typo3.org/typo3cms/exceptions/main/en-us/Exceptions/1616175847.html
  *  page source: https://docs.typo3.org/typo3cms/exceptions/main/en-us/_sources/Exceptions/1616175847.rst.txt 

![image](https://user-images.githubusercontent.com/13206455/233831224-9ffb35c4-622a-4112-8eac-61a29fba7c88.png)

* see other page source: https://docs.typo3.org/typo3cms/exceptions/main/en-us/_sources/Exceptions/1476107295.rst.txt

**Comment by linawolf** [comment]
@sypets yes, that is something we always fight against and they are hard to detect automatically. If you run across one, could you provide a PR please?
