### ISSUE TITLE
[TASK] Implement automatic exception code determination and page creation

### ISSUE THREAD

**Issue by sbuerk** [TYPO3-Documentation/TYPO3CMS-Exceptions#128]
The repository https://github.com/TYPO3-Documentation/t3docs-exception-pages
provided a application to create missing exception code pages in this repository,
wrapped around a emulated web application simulating core exception code pages.

No current active contributor really knows the deployment ways, and it seams that
the web application kickof is not used by contributors directly.

Therefore, the logic to scan TYPO3 core releases for exception codes and than ensure
that corresponding exception code pages are created based on an template should be
added directly to this repository.

That eleminates a (under) documented system no one really understands and a complex,
splitted workflow.

The tool should be usable locally but also as a automatic GitHub Action workflow in
a scheduled fashion to remove the human interaction requirement after TYPO3 releases.

**Comment by sypets** [comment]
Might also be a good idea if some monitoring is in place so someone gets notified if things stop working.
