### ISSUE TITLE
Link broken on Exceptions 1616175867 page

### ISSUE THREAD

**Issue by n3amil** [TYPO3-Documentation/TYPO3CMS-Exceptions#96]
https://docs.typo3.org/typo3cms/exceptions/main/en-us/Exceptions/1616175867.html

See also: [:docs:`t3coreapi:Changelog/11.3/Feature-93825-RateLimitingForFailedLogins.html`](https://docs.typo3.org/typo3cms/exceptions/main/en-us/Exceptions/1616175867.html#id2).

points to the exception page itself. I guess it should be https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.3/Feature-93825-RateLimitingForFailedLogins.html

**Comment by brotkrueml** [comment]
Thank you for reporting :-)
